name: CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE || secrets.GITHUB_TOKEN || secrets.GH_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup
        with:
          GH_TOKEN: ${{ env.GH_TOKEN }}

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup
        with:
          GH_TOKEN: ${{ env.GH_TOKEN }}

      - name: Run unit tests
        run: yarn test

  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup
        with:
          GH_TOKEN: ${{ env.GH_TOKEN }}

      - name: Build package
        run: yarn prepack

      - name: Create release
        run: yarn release
